from __future__ import annotations

from pathlib import Path

from scripts.check_repo_hygiene import find_violations


def test_rejects_handoff_filename(tmp_path: Path) -> None:
    path = Path("docs/handoff-example.md")
    (tmp_path / path).parent.mkdir(parents=True)
    (tmp_path / path).write_text("session state\n")
    assert find_violations(tmp_path, [path]) == [
        "docs/handoff-example.md: prohibited handoff file"
    ]


def test_rejects_coding_tool_name(tmp_path: Path) -> None:
    path = Path("module.py")
    (tmp_path / path).write_text("# generated by " + "co" + "dex" + "\n")
    assert find_violations(tmp_path, [path]) == [
        "module.py:1: prohibited coding-tool name"
    ]


def test_allows_runtime_model_dependency_path(tmp_path: Path) -> None:
    path = Path("agents/ops_copilot/runtime.py")
    (tmp_path / path).parent.mkdir(parents=True)
    (tmp_path / path).write_text("model = '" + "clau" + "de-runtime'\n")
    assert find_violations(tmp_path, [path]) == []


def test_accepts_clean_file(tmp_path: Path) -> None:
    path = Path("module.py")
    (tmp_path / path).write_text("print('clean')\n")
    assert find_violations(tmp_path, [path]) == []
